---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-niri-noctalia
# description will be included in the image's metadata
description: A personal Fedora Atomic desktop image built around Niri and Noctalia.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  - type: dnf
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      copr:
        - atim/starship
    install:
      packages:
        - 7zip
        - alacritty
        - bluez
        - brave-origin
        - brightnessctl
        - chezmoi
        - distrobox
        - fish
        - git
        - gnome-keyring
        - google-noto-color-emoji-fonts
        - google-noto-sans-vf-fonts
        - google-noto-serif-vf-fonts
        - greetd
        - greetd-selinux
        - gvfs-fuse
        - gvfs-mtp
        - NetworkManager
        - NetworkManager-wifi
        - neovim
        - niri
        - noctalia
        - openssh-clients
        - pipewire
        - pipewire-pulseaudio
        - playerctl
        - podman
        - polkit
        - rsms-inter-fonts
        - starship
        - swayimg
        - Thunar
        - thunar-archive-plugin
        - thunar-volman
        - tmux
        - tuigreet
        - unzip
        - wireplumber
        - wl-clipboard
        - xarchiver
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xdg-utils
        - zip

    remove:
      packages:
        # base-main normally does not include Firefox; remove it defensively in case that changes upstream
        - firefox
        - firefox-langpacks
  
  - type: fonts
    fonts:
      nerd-fonts:
        - IosevkaTerm
        
  - type: systemd
    system:
      enabled:
        - greetd.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user # Add Flathub user repo

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
